#!/bin/sh
# /etc/init.d/conky_init

### BEGIN INIT INFO
# Provides:            conky
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Start conky
# Description:         Start conky
### END INIT INFO


sleep 30
conky -c $HOME/.config/conky/conkyrc_grey -a top_left -x 0 -y 40 -d &

exit 0
